-- Supabase schema draft for catalog migration.
-- This draft is derived from backend/common JPA entities and current query patterns.

create extension if not exists pg_trgm;

create table if not exists public.liquor_info (
    id bigint generated by default as identity primary key,
    brand text,
    category text,
    alcohol_percent double precision,
    volume_ml integer,
    clazz text
);

create table if not exists public.liquor (
    id bigint generated by default as identity primary key,
    normalized_name text not null,
    brand text,
    category text,
    volume_ml integer,
    alcohol_percent double precision,
    country text,
    "class" text,
    product_code text,
    product_name text,
    product_url text,
    image_url text,
    liquor_info_id bigint references public.liquor_info (id),
    sweet double precision,
    smoky double precision,
    fruity double precision,
    spicy double precision,
    woody double precision,
    body double precision,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.liquor_price (
    id bigint generated by default as identity primary key,
    liquor_id bigint not null references public.liquor (id) on delete cascade,
    source text not null,
    current_price integer,
    original_price integer,
    crawled_at timestamptz not null default now()
);

create unique index if not exists uq_liquor_product_code
    on public.liquor (product_code)
    where product_code is not null and btrim(product_code) <> '';

create unique index if not exists uq_liquor_identity
    on public.liquor (
        normalized_name,
        coalesce("class", ''),
        coalesce(volume_ml, 0)
    );

create unique index if not exists uq_liquor_price_source
    on public.liquor_price (liquor_id, source);

create index if not exists idx_liquor_updated_at
    on public.liquor (updated_at desc);

create index if not exists idx_liquor_price_crawled_at
    on public.liquor_price (crawled_at desc);

create index if not exists idx_liquor_price_lookup
    on public.liquor_price (liquor_id, crawled_at desc);

create index if not exists idx_liquor_info_brand_category_volume
    on public.liquor_info (brand, category, volume_ml);

create index if not exists idx_liquor_search_product_name_trgm
    on public.liquor using gin (lower(coalesce(product_name, '')) gin_trgm_ops);

create index if not exists idx_liquor_search_normalized_name_trgm
    on public.liquor using gin (lower(coalesce(normalized_name, '')) gin_trgm_ops);

create index if not exists idx_liquor_search_brand_trgm
    on public.liquor using gin (lower(coalesce(brand, '')) gin_trgm_ops);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists trg_liquor_set_updated_at on public.liquor;

create trigger trg_liquor_set_updated_at
before update on public.liquor
for each row
execute function public.set_updated_at();

create or replace view public.liquor_catalog_latest_price as
select distinct on (lp.liquor_id)
    l.id,
    l.normalized_name,
    l.brand,
    l.category,
    l.volume_ml,
    l.alcohol_percent,
    l.country,
    l.product_code,
    l.product_name,
    l.product_url,
    l.image_url,
    l.updated_at,
    lp.source,
    lp.current_price,
    lp.original_price,
    lp.crawled_at
from public.liquor_price lp
join public.liquor l on l.id = lp.liquor_id
order by lp.liquor_id, lp.crawled_at desc;
